### ISSUE TITLE
Notebooks not cleaned when staged for git commit

### ISSUE THREAD

**Issue by bluginbuhl-enthought** [srstevenson/nb-clean#68] opened 2021-06-02 23:36 UTC
# Issue

Following the documentation to add a `git` filter by running `nb-clean add-filter` correctly creates/modifies the `/.git/info/attributes` and `/.git/config` files. However, notebooks that are staged for commit are not cleaned by the filter.

## Expected Behavior

After running `nb-clean add-filter` in the root directory of the `git` repo, any notebooks staged for a commit should be cleaned by the filter prior to staging.

Setup: a new `git` repository has been created by running `git init`. `nb-clean` has been installed by running `pip install nb-clean`, and the `nb-clean add-filter` command has been run. The correct `git` files have been modified:

```
# .git/info/attributes

*.ipynb filter=nb-clean

```

```
# .git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[filter "nb-clean"]
	clean = nb-clean clean

```

Create a new `jupyter notebook` and add some data.

Output for an unstaged notebook, `test_notebook.ipynb`:
```
$ cat test_notebook.ipynb
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ce5c1671",
   "metadata": {},
   "outputs": [],
   "source": [
    "import time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "0f43b93d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "5.005712509155273\n"
     ]
    }
   ],
   "source": [
    "time_start = time.time()\n",
    "time.sleep(5)\n",
    "print(time.time() - time_start)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "19ff96fb",
   "metadata": {},
   "source": [
    "# This is a markdown cell\n",
    "\n",
    "### Blah blah blah\n",
    "\n",
    "<a href=\"#\" target=\"_blank\">Link with HTML formatting</a>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "b5364b1b",
   "metadata": {},
   "outputs": [],
   "source": [
    "# running many executions"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c65a168c",
   "metadata": {},
   "source": [
    "The following is an empty cell to test `nb-clean clean --remove-empty-cells`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f99d74b9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
```

```
$ git status
On branch main
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        test_notebook1.ipynb

nothing added to commit but untracked files present (use "git add" to track)
```

Run `git add test_notebook.ipynb`.

```
$ git status
On branch main
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   test_notebook1.ipynb
```

Run : 

```
$ nb-clean check test_notebook.ipynb
test_notebook1.ipynb cell 0: execution count
test_notebook1.ipynb cell 1: execution count
test_notebook1.ipynb cell 1: outputs
test_notebook1.ipynb cell 3: execution count
```

## Suggested Fix

The `.git/config` file should be modified as follows:

```
...
[filter "nb-clean"]
    clean = nb-clean clean %f

```

This will run the `clean` function for every file that matches the filter described in the `.git/info/attributes` file. It might also be nice to include `required = true` after the `clean` definition.

Further, it would be nice if the `clean` function made the modifications to the `*.ipynb` files in-place, rather than making the changes and not adding them to the commit. As it is now, adding the files to a commit will only add the pre-filtered notebooks to the staging area, while the modified version is left out, meaning the user has to re-add the notebooks to the commit (assuming that the above fix is implemented). See the following articles for more explanation:

* [Making Git and Jupyter Notebooks play nice](http://timstaley.co.uk/posts/making-git-and-jupyter-notebooks-play-nice/)
* [Clearing Output Data in Jupyter Notebooks using Git Attributes](https://zhauniarovich.com/post/2020/2020-10-clearing-jupyter-output-p3/)

## Information

`OS` :  Ubuntu 20.04 (running on WSL2)

| program | version |
|-:|:-|
|`Python` | 3.6.13 |
| `git`  | 2.25.1 |
| `nb-clean` |  2.0.2 |

**Comment by srstevenson** [comment] 2021-06-06 16:57
Thanks for the clear report @bluginbuhl-enthought! nb-clean is working as designed here, although differently from what you expected.

Notebooks matching the pattern in the attributes file are piped to nb-clean on standard input, which cleans the blob which is added to the index but doesn't mutate the working copy (hence why we don't use the `%f` placeholder). After you call `git add test_notebook.ipynb`, the working copy is unchanged and still contains output:

```bash
$ nb-clean check test_notebook.ipynb 
test_notebook.ipynb cell 0: execution count
test_notebook.ipynb cell 1: execution count
test_notebook.ipynb cell 1: outputs
test_notebook.ipynb cell 3: execution count
```

but the blob which has been staged and will be committed to the repository is clean:
```bash
$ git status -s
A  test_notebook.ipynb
$ git show :test_notebook.ipynb | nb-clean check
```

The reason for this design design is so output such as plots which might be expensive to recompute or you're still referencing aren't lost as you stage incremental changes, and to avoid the warnings from Jupyter when it sees the notebook on disk has been changed by another process.

> It might also be nice to include required = true after the clean definition.

I chose not to include this as the docs say its purpose is to "declare that a filter turns a content that by itself is unusable into a usable content". My interpretation was this makes sense for something like a filter which decrypts files as they're checked out as ciphertext itself is unusable, but for nb-clean the output is still "usable" either clean or not. What are your thoughts on this?

**Comment by bluginbuhl-enthought** [comment] 2021-06-09 21:34
Hi Scott, thanks for the response! You're right, I misunderstood exactly what was happening under the hood with the staging vs. commit.

And you're right regarding the `required` flag for the filter - this should be up to whomever uses the package to set for their own repositories, if they desire.

**Comment by bluginbuhl-enthought** [comment] 2021-06-09 21:40
Actually, one more quick thing - do you know how `git stash` interacts with this package? Will the blog also get cleaned when a notebook is stashed, and will it be restored to it's previous state when `pop`ing?

**Closed** 2021-06-10 15:20 UTC
